### ISSUE TITLE
[BUG] Chargement des automates depuis menu

### ISSUE THREAD

**Issue by mathuld** [hughnatt/projet-pla#52]
_Lorsqu'on change d'automate dans le menu, il faut redémarrer le jeu sinon les modifications ne sont pas prises en compte._ 

**Exemple pour tester le bug :**
Dans le fichier choix_automates.txt mettre des 0 sur les lignes 1 à 6
Allumer le jeu
Changer l'automate du projectile pour qu'il utilise bien l'automate projectile
Cliquer sur jouer
Le projectile a toujours l'automate du joueur

Redémarrer le jeu
Cliquer sur jouer
Le projectile à le bon automate

**Comment by hughnatt** [comment]
Corrigé dans branche dev-choiceauto
