### ISSUE TITLE
Plusieurs projectiles sur la même case lors du tir (espace)

### ISSUE THREAD

**Issue by mathuld** [hughnatt/projet-pla#76]
Lorsqu'on laisse la touche espace enfoncée il peut y avoir plusieurs projectiles sur la même case. On ne voit pas vraiment le problème au niveau des sprites mais l'entitée touchée prend plus de dégâts.

**Comment by hughnatt** [comment]
On va mettre un anti-spam sur le hit du player

**Comment by hughnatt** [comment]
Implémenté dans dev-bugfixes
