### ISSUE TITLE
Sélection automates ne fonctionne pas

### ISSUE THREAD

**Issue by mathuld** [hughnatt/projet-pla#94]
Les entitées ne chargent pas les bons automates

**Comment by hughnatt** [comment]
FAUX PROBLEME.
LE ENTITES QUI NE BOUGENT PAS N4ONT PAS LA LIGNE M8AUTOMATA.STEP DANS LEUR STEP DONC FORCEMENT CA MARCHE PAAASS.

**Comment by hughnatt** [comment]
Solvé sur pétrole

**Comment by hughnatt** [comment]
Corrigé (vraiment) sur dev-bugfix2
